name: Run expreccs executable

on:
 push:
   branches:
     - main
 pull_request:
   
jobs:
  run-pyff-local:
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8']
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Flow Simulator
      run: |
        sudo apt-get update -y
        sudo apt-get install software-properties-common
        sudo apt-get install -y build-essential gfortran pkg-config cmake
        sudo apt-get install -y mpi-default-dev
        sudo apt-get install -y libblas-dev libboost-all-dev libsuitesparse-dev libtrilinos-zoltan-dev
        chmod u+x build_dune_and_opm-flow.bash
        ./build_dune_and_opm-flow.bash
        alias flow='/home/runner/work/expreccs/expreccs/build/opm-simulators/bin/flow_gasoil'
        
    - name: Install test dependecies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -r dev-requirements.txt
        
    - name: Install expreccs
      run: |
        pip install .
        
    - name: Check code style and linting 
      run: |
        black --check src/ tests/ setup.py
        pylint src/ tests/ setup.py
        mypy --ignore-missing-imports src/ tests/ setup.py
      
    - name: Run the tests
      run: |
        pytest --cov=expreccs --cov-report term-missing tests/
        
    - name: Build documentation
      run: |
        pushd docs
        make html
